Update README.md
Pelagicore/PeluxDeviceManager pull request #3
Opened 2017-07-17 16:03 UTC by caybro

explain the dependencies in more detail
fixes issue #2

2017-07-18 10:52 UTC, zeenix reviewed
Changes are good but commit log can be much better.

2017-07-18 11:02 UTC, zeenix requested changes
Sorry i accidently hit the submit button. I was going to say what needs fixing. :)

* "Update" is pretty vague.
* The details section is supposed to be normal English so
  * Capitalize the first e.
  * Finish sentences with '.'.
  * The only valid reasons to break into newline is to start a new para (by leaving a blank line in between) or exceeding the character limit (which is 75). :)

Sorry to point to a GNOME wiki but we have agreed to follow these guidelines: https://wiki.gnome.org/Git/CommitMessages/

2017-07-18 11:11 UTC, caybro commented
@zeenix Objections addressed I believe

2017-07-18 11:14 UTC, zeenix commented
@caybro Thanks! I wouldn't call them "objections" though. :-)

2017-07-18 11:14 UTC, zeenix commented
@caybro The commit remains the same, you probably forgot to push?

2017-07-18 11:17 UTC, GordanM requested changes

2017-07-18 11:17 UTC, GordanM commented on README.md
> +  - manual build: usually just a matter of `sudo apt build-dep solid` for Ubuntu or `sudo dnf builddep kf5-solid` for Fedora
`sudo apt build-dep solid` doesn't seem to work unless I have populated the sources.list with the location of the solid source code.

```
➜  poky git:(pyro) sudo apt build-dep libkf5solid
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
```

2017-07-18 11:51 UTC, caybro commented on README.md
> +  - manual build: usually just a matter of `sudo apt build-dep solid` for Ubuntu or `sudo dnf builddep kf5-solid` for Fedora
https://wiki.documentfoundation.org/Development/Linux_Build_Dependencies#Debian_.2F_Ubuntu

2017-07-18 12:51 UTC, zeenix commented
@caybro Thanks but merges makes things difficult to read. Please rebase and squash.

2017-07-18 12:53 UTC, zeenix commented
oh and you'll need to do a forced push to your branch.

2017-07-18 12:53 UTC, GordanM commented
@zeenix I've disabled merge commits for this repository, it should not be possible to do so.

2017-07-18 12:59 UTC, rpannek commented
I'd like to link https://pelagicore.github.io/software-factory/chapters/workflow/git-workflow.html here where we explain the workflow with private forks and pull requests, etc.

2017-07-18 13:02 UTC, zeenix commented
@rpannek thanks and I'll add a section about recommendation for good commit messages to that chapter too.

2017-07-19 09:05 UTC, caybro commented
@zeenix rebased and squashed the commits, should be good now

2017-07-19 11:26 UTC, rpannek approved these changes

2017-07-19 11:31 UTC, zeenix approved these changes

2017-07-19 11:32 UTC, merged